# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.4"
  # CUSTOMIZE HERE
  #! VERY IMPORTANT: You should NOT config host port < 1024 because of a rule of linux
  config.vm.network :forwarded_port, guest: 9999, host: 9999
  # CUSTOMIZE HERE
  config.vm.network "private_network", ip: "192.168.77.100"
  # CUSTOMIZE HERE
  config.vm.provider :virtualbox do |v|
    v.name = "manage-ip"
    v.memory = 512
    v.cpus = 1
  end

  config.vbguest.auto_update = false
  # CUSTOMIZE HERE
  config.vm.hostname = "vagrant-base-box"
end
